# Use official Spark image
FROM apache/spark:3.5.0

# Switch to root to install JARs
USER root

# Download Hadoop AWS connector + AWS SDK
RUN wget -q https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.3.6/hadoop-aws-3.3.6.jar -P $SPARK_HOME/jars/ \
 && wget -q https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.12.367/aws-java-sdk-bundle-1.12.367.jar -P $SPARK_HOME/jars/ \
 && chmod 644 $SPARK_HOME/jars/*.jar

# Switch back to spark user
USER spark